In [82]:
# !pip install numpy

In [83]:
import numpy as np

In [84]:
mylist=[1,2,3,4,5]
n=np.array(mylist)
n

array([1, 2, 3, 4, 5])

In [85]:
type(n)

numpy.ndarray

In [86]:
n=np.array([1,2,3,4,5])
n

array([1, 2, 3, 4, 5])

In [87]:
list_of_list=np.array([[1,2,3],[4,5,6],[7,8,9]])
list_of_list

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [88]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [91]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [92]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [93]:
mn=np.arange(0,50)
mn

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [94]:
len(mn)

50

In [95]:
mn.reshape(5,10)  #reshape cant alters the orginal

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [96]:
mn

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [97]:
o=np.linspace(0,7,10)
o

array([0.        , 0.77777778, 1.55555556, 2.33333333, 3.11111111,
       3.88888889, 4.66666667, 5.44444444, 6.22222222, 7.        ])

In [98]:
o.resize(5,2)   #resize alters the original but reshape will not
o

array([[0.        , 0.77777778],
       [1.55555556, 2.33333333],
       [3.11111111, 3.88888889],
       [4.66666667, 5.44444444],
       [6.22222222, 7.        ]])

In [99]:
o

array([[0.        , 0.77777778],
       [1.55555556, 2.33333333],
       [3.11111111, 3.88888889],
       [4.66666667, 5.44444444],
       [6.22222222, 7.        ]])

In [100]:
np.random.rand(5,3) #generates a sample of no's from 'uniform distribution' [0,1]

array([[0.55359004, 0.33416031, 0.82603965],
       [0.6253702 , 0.00984503, 0.30049749],
       [0.89947512, 0.46536796, 0.02922525],
       [0.47723028, 0.32686574, 0.05070496],
       [0.66363867, 0.59809381, 0.98353792]])

In [101]:
np.random.randn(5,3)  #generates a sample of no's from 'standard normal distribution'

array([[-0.40171223, -0.36954634,  1.09433978],
       [ 0.84541809,  0.69046808, -0.13134045],
       [-0.12189594, -1.07193987,  0.02303158],
       [-0.16766671,  1.19970608,  1.544895  ],
       [-0.72262449,  0.52288423, -0.71995373]])

In [102]:
 np.random.randint(2,20,10)  #generates a sample from a given range

array([13, 19,  2,  9,  3, 11,  8, 18, 16,  9])

In [103]:
 np.random.randint(2,20, (5,2))

array([[ 9, 11],
       [14,  3],
       [14,  9],
       [10,  7],
       [ 3,  2]])

# Indexing and Slicing

In [104]:
mn=np.random.randint(4,15,10)
mn

array([ 9, 13,  8, 13,  9,  6, 12, 12, 11,  4])

In [105]:
mn[1]

13

In [106]:
mn[-1]

4

In [107]:
mn[3:7] #selecting item within a range

array([13,  9,  6, 12])

In [108]:
mn[3:]

array([13,  9,  6, 12, 12, 11,  4])

In [109]:
mn[5:-2]

array([ 6, 12, 12])

In [110]:
a=np.arange(64)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [111]:
a.resize(8,8)

In [112]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [113]:
a[2,3]

19

In [114]:
a[4,2:5]

array([34, 35, 36])

In [74]:
a[3:]

array([[24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [75]:
a[3:,3:]

array([[27, 28, 29, 30, 31],
       [35, 36, 37, 38, 39],
       [43, 44, 45, 46, 47],
       [51, 52, 53, 54, 55],
       [59, 60, 61, 62, 63]])

In [76]:
a[a>17]  #conditional indexing

array([18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [77]:
a[a>25]=25   #casting all the values that are greater than 25 to 25 is called broadcasting
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25]])

## Creating a copy

In [78]:
a1=a[3:,3:]
a1

array([[25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25]])

In [79]:
a_copy=a.copy()

In [80]:
a_copy

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25]])